[package]
name = "swimrs"
version = "0.1.0"
authors = ["Pierce Bartine <pbar1@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "cookies"] }
tokio = { version = "1", features = ["full"] }
clap = "3.0.0-beta.2"
strum = { version = "0.21", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
