[package]
name = "swimrs-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive", "wrap_help"] }
swimrs = { path = "../swimrs" }
tokio = { version = "1", features = ["full"] }
